export const FETCH_AGREEMENTS_REQUEST = "FETCH_AGREEMENTS_REQUEST";
export const FETCH_AGREEMENTS_ERROR = "FETCH_AGREEMENTS_ERROR";
export const FETCH_AGREEMENTS_SUCCESS = "FETCH_AGREEMENTS_SUCCESS";

export const CREATE_AGREEMENT_REQUEST = "CREATE_AGREEMENT_REQUEST";
export const CREATE_AGREEMENT_ERROR = "CREATE_AGREEMENT_ERROR";
export const CREATE_AGREEMENT_SUCCESS = "CREATE_AGREEMENT_SUCCESS";

export const DELETE_AGREEMENT_REQUEST = "DELETE_AGREEMENT_REQUEST";
export const DELETE_AGREEMENT_ERROR = "DELETE_AGREEMENT_ERROR";
export const DELETE_AGREEMENT_SUCCESS = "DELETE_AGREEMENT_SUCCESS";

export const UPDATE_AGREEMENT_REQUEST = "UPDATE_AGREEMENT_REQUEST";
export const UPDATE_AGREEMENT_ERROR = "UPDATE_AGREEMENT_ERROR";
export const UPDATE_AGREEMENT_SUCCESS = "UPDATE_AGREEMENT_SUCCESS";

export const FETCH_AGREEMENT_REQUEST = "FETCH_AGREEMENT_REQUEST";
export const FETCH_AGREEMENT_ERROR = "FETCH_AGREEMENT_ERROR";
export const FETCH_AGREEMENT_SUCCESS = "FETCH_AGREEMENT_SUCCESS";

export const EDIT_AGREEMENT = "EDIT_AGREEMENT";
export const RESET_AGREEMENT_FORM = "RESET_AGREEMENT_FORM";
export const SEARCH_AGREEMENTS = "SEARCH_AGREEMENTS";
export const SET_FILTER_AGREEMENTS = "INSTALL_FILTER_AGREEMENTS";
export const RESET_FILTER_AGREEMENTS = "RESET_FILTER_AGREEMENTS";
