export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_ERROR = "CREATE_CONTACT_ERROR";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";

export const FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST";
export const FETCH_CONTACT_ERROR = "FETCH_CONTACT_ERROR";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";

export const EDIT_CONTACT = "EDIT_CONTACT";
export const RESET_CONTACT_FORM = "RESET_CONTACT_FORM";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
export const SET_FILTER_CONTACTS= "SET_FILTER_CONTACTS";
export const RESET_FILTER_CONTACTS = "RESET_FILTER_CONTACTS";