export const FETCH_GROUP_NOMENCLATURES_REQUEST = "FETCH_GROUP_NOMENCLATURES_REQUEST";
export const FETCH_GROUP_NOMENCLATURES_ERROR = "FETCH_GROUP_NOMENCLATURES_ERROR";
export const FETCH_GROUP_NOMENCLATURES_SUCCESS = "FETCH_GROUP_NOMENCLATURES_SUCCESS";

export const CREATE_GROUP_NOMENCLATURE_REQUEST = "CREATE_GROUP_NOMENCLATURE_REQUEST";
export const CREATE_GROUP_NOMENCLATURE_ERROR = "CREATE_GROUP_NOMENCLATURE_ERROR";
export const CREATE_GROUP_NOMENCLATURE_SUCCESS = "CREATE_GROUP_NOMENCLATURE_SUCCESS";

export const DELETE_GROUP_NOMENCLATURE_REQUEST = "DELETE_GROUP_NOMENCLATURE_REQUEST";
export const DELETE_GROUP_NOMENCLATURE_ERROR = "DELETE_GROUP_NOMENCLATURE_ERROR";
export const DELETE_GROUP_NOMENCLATURE_SUCCESS = "DELETE_GROUP_NOMENCLATURE_SUCCESS";

export const UPDATE_GROUP_NOMENCLATURE_REQUEST = "UPDATE_GROUP_NOMENCLATURE_REQUEST";
export const UPDATE_GROUP_NOMENCLATURE_ERROR = "UPDATE_GROUP_NOMENCLATURE_ERROR";
export const UPDATE_GROUP_NOMENCLATURE_SUCCESS = "UPDATE_GROUP_NOMENCLATURE_SUCCESS";

export const FETCH_GROUP_NOMENCLATURE_REQUEST = "FETCH_GROUP_NOMENCLATURE_REQUEST";
export const FETCH_GROUP_NOMENCLATURE_ERROR = "FETCH_GROUP_NOMENCLATURE_ERROR";
export const FETCH_GROUP_NOMENCLATURE_SUCCESS = "FETCH_GROUP_NOMENCLATURE_SUCCESS";

export const EDIT_GROUP_NOMENCLATURE = "EDIT_GROUP_NOMENCLATURE";
export const RESET_GROUP_NOMENCLATURE_FORM = "RESET_GROUP_NOMENCLATURE_FORM";
export const SEARCH_GROUP_NOMENCLATURES = "SEARCH_GROUP_NOMENCLATURES";