export const FETCH_NOMENCLATURES_REQUEST = "FETCH_NOMENCLATURES_REQUEST";
export const FETCH_NOMENCLATURES_ERROR = "FETCH_NOMENCLATURES_ERROR";
export const FETCH_NOMENCLATURES_SUCCESS = "FETCH_NOMENCLATURES_SUCCESS";

export const CREATE_NOMENCLATURE_REQUEST = "CREATE_NOMENCLATURE_REQUEST";
export const CREATE_NOMENCLATURE_ERROR = "CREATE_NOMENCLATURE_ERROR";
export const CREATE_NOMENCLATURE_SUCCESS = "CREATE_NOMENCLATURE_SUCCESS";

export const DELETE_NOMENCLATURE_REQUEST = "DELETE_NOMENCLATURE_REQUEST";
export const DELETE_NOMENCLATURE_ERROR = "DELETE_NOMENCLATURE_ERROR";
export const DELETE_NOMENCLATURE_SUCCESS = "DELETE_NOMENCLATURE_SUCCESS";

export const UPDATE_NOMENCLATURE_REQUEST = "UPDATE_NOMENCLATURE_REQUEST";
export const UPDATE_NOMENCLATURE_ERROR = "UPDATE_NOMENCLATURE_ERROR";
export const UPDATE_NOMENCLATURE_SUCCESS = "UPDATE_NOMENCLATURE_SUCCESS";

export const FETCH_NOMENCLATURE_REQUEST = "FETCH_NOMENCLATURE_REQUEST";
export const FETCH_NOMENCLATURE_ERROR = "FETCH_NOMENCLATURE_ERROR";
export const FETCH_NOMENCLATURE_SUCCESS = "FETCH_NOMENCLATURE_SUCCESS";

export const EDIT_NOMENCLATURE = "EDIT_NOMENCLATURE";
export const RESET_NOMENCLATURE_FORM = "RESET_NOMENCLATURE_FORM";
export const SEARCH_NOMENCLATURES = "SEARCH_NOMENCLATURES";