export const FETCH_ORGANIZATIONS_REQUEST = "FETCH_ORGANIZATIONS_REQUEST";
export const FETCH_ORGANIZATIONS_ERROR = "FETCH_ORGANIZATIONS_ERROR";
export const FETCH_ORGANIZATIONS_SUCCESS = "FETCH_ORGANIZATIONS_SUCCESS";

export const CREATE_ORGANIZATION_REQUEST = "CREATE_ORGANIZATION_REQUEST";
export const CREATE_ORGANIZATION_ERROR = "CREATE_ORGANIZATION_ERROR";
export const CREATE_ORGANIZATION_SUCCESS = "CREATE_ORGANIZATION_SUCCESS";

export const DELETE_ORGANIZATION_REQUEST = "DELETE_ORGANIZATION_REQUEST";
export const DELETE_ORGANIZATION_ERROR = "DELETE_ORGANIZATION_ERROR";
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS";

export const UPDATE_ORGANIZATION_REQUEST = "UPDATE_ORGANIZATION_REQUEST";
export const UPDATE_ORGANIZATION_ERROR = "UPDATE_ORGANIZATION_ERROR";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";

export const FETCH_ORGANIZATION_REQUEST = "FETCH_ORGANIZATION_REQUEST";
export const FETCH_ORGANIZATION_ERROR = "FETCH_ORGANIZATION_ERROR";
export const FETCH_ORGANIZATION_SUCCESS = "FETCH_ORGANIZATION_SUCCESS";

export const EDIT_ORGANIZATION = "EDIT_ORGANIZATION";
export const RESET_ORGANIZATION_FORM = "RESET_ORGANIZATION_FORM";
export const SEARCH_ORGANIZATIONS = "SEARCH_ORGANIZATIONS";
export const SET_FILTER_ORGANIZATIONS="SET_FILTER_ORGANIZATIONS";
export const RESET_FILTER_ORGANIZATIONS="RESET_FILTER_ORGANIZATIONS";