export const FETCH_PHONES_REQUEST = "FETCH_PHONES_REQUEST";
export const FETCH_PHONES_ERROR = "FETCH_PHONES_ERROR";
export const FETCH_PHONES_SUCCESS = "FETCH_PHONES_SUCCESS";

export const CREATE_PHONE_REQUEST = "CREATE_PHONE_REQUEST";
export const CREATE_PHONE_ERROR = "CREATE_PHONE_ERROR";
export const CREATE_PHONE_SUCCESS = "CREATE_PHONE_SUCCESS";

export const DELETE_PHONE_REQUEST = "DELETE_PHONE_REQUEST";
export const DELETE_PHONE_ERROR = "DELETE_PHONE_ERROR";
export const DELETE_PHONE_SUCCESS = "DELETE_PHONE_SUCCESS";

export const UPDATE_PHONE_REQUEST = "UPDATE_PHONE_REQUEST";
export const UPDATE_PHONE_ERROR = "UPDATE_PHONE_ERROR";
export const UPDATE_PHONE_SUCCESS = "UPDATE_PHONE_SUCCESS";

export const FETCH_PHONE_REQUEST = "FETCH_PHONE_REQUEST";
export const FETCH_PHONE_ERROR = "FETCH_PHONE_ERROR";
export const FETCH_PHONE_SUCCESS = "FETCH_PHONE_SUCCESS";

export const EDIT_PHONE = "EDIT_PHONE";
export const RESET_PHONE_FORM = "RESET_PHONE_FORM";
export const SEARCH_PHONES = "SEARCH_PHONES";
export const SET_FILTER_PHONES = "INSTALL_FILTER_PHONES";
export const RESET_FILTER_PHONES= "RESET_FILTER_PHONES";
