export const FETCH_POSITIONS_REQUEST = "FETCH_POSITIONS_REQUEST";
export const FETCH_POSITIONS_ERROR = "FETCH_POSITIONS_ERROR";
export const FETCH_POSITIONS_SUCCESS = "FETCH_POSITIONS_SUCCESS";

export const CREATE_POSITION_REQUEST = "CREATE_POSITION_REQUEST";
export const CREATE_POSITION_ERROR = "CREATE_POSITION_ERROR";
export const CREATE_POSITION_SUCCESS = "CREATE_POSITION_SUCCESS";

export const DELETE_POSITION_REQUEST = "DELETE_POSITION_REQUEST";
export const DELETE_POSITION_ERROR = "DELETE_POSITION_ERROR";
export const DELETE_POSITION_SUCCESS = "DELETE_POSITION_SUCCESS";

export const UPDATE_POSITION_REQUEST = "UPDATE_POSITION_REQUEST";
export const UPDATE_POSITION_ERROR = "UPDATE_POSITION_ERROR";
export const UPDATE_POSITION_SUCCESS = "UPDATE_POSITION_SUCCESS";

export const FETCH_POSITION_REQUEST = "FETCH_POSITION_REQUEST";
export const FETCH_POSITION_ERROR = "FETCH_POSITION_ERROR";
export const FETCH_POSITION_SUCCESS = "FETCH_POSITION_SUCCESS";

export const EDIT_POSITION = "EDIT_POSITION";
export const RESET_POSITION_FORM = "RESET_POSITION_FORM";
export const SEARCH_POSITIONS = "SEARCH_POSITIONS";
