export const FETCH_TYPE_OF_AGREEMENTS_REQUEST =
  "FETCH_TYPE_OF_AGREEMENTS_REQUEST";
export const FETCH_TYPE_OF_AGREEMENTS_ERROR = "FETCH_TYPE_OF_AGREEMENTS_ERROR";
export const FETCH_TYPE_OF_AGREEMENTS_SUCCESS =
  "FETCH_TYPE_OF_AGREEMENTS_SUCCESS";

export const CREATE_TYPE_OF_AGREEMENT_REQUEST =
  "CREATE_TYPE_OF_AGREEMENT_REQUEST";
export const CREATE_TYPE_OF_AGREEMENT_ERROR = "CREATE_TYPE_OF_AGREEMENT_ERROR";
export const CREATE_TYPE_OF_AGREEMENT_SUCCESS =
  "CREATE_TYPE_OF_AGREEMENT_SUCCESS";

export const DELETE_TYPE_OF_AGREEMENT_REQUEST =
  "DELETE_TYPE_OF_AGREEMENT_REQUEST";
export const DELETE_TYPE_OF_AGREEMENT_ERROR = "DELETE_TYPE_OF_AGREEMENT_ERROR";
export const DELETE_TYPE_OF_AGREEMENT_SUCCESS =
  "DELETE_TYPE_OF_AGREEMENT_SUCCESS";

export const UPDATE_TYPE_OF_AGREEMENT_REQUEST =
  "UPDATE_TYPE_OF_AGREEMENT_REQUEST";
export const UPDATE_TYPE_OF_AGREEMENT_ERROR = "UPDATE_TYPE_OF_AGREEMENT_ERROR";
export const UPDATE_TYPE_OF_AGREEMENT_SUCCESS =
  "UPDATE_TYPE_OF_AGREEMENT_SUCCESS";

export const FETCH_TYPE_OF_AGREEMENT_REQUEST =
  "FETCH_TYPE_OF_AGREEMENT_REQUEST";
export const FETCH_TYPE_OF_AGREEMENT_ERROR = "FETCH_TYPE_OF_AGREEMENT_ERROR";
export const FETCH_TYPE_OF_AGREEMENT_SUCCESS =
  "FETCH_TYPE_OF_AGREEMENT_SUCCESS";

export const EDIT_TYPE_OF_AGREEMENT = "EDIT_TYPE_OF_AGREEMENT";
export const RESET_TYPE_OF_AGREEMENT_FORM = "RESET_TYPE_OF_AGREEMENT_FORM";
export const SEARCH_TYPE_OF_AGREEMENTS = "SEARCH_TYPE_OF_AGREEMENTS";
