export const FETCH_TYPE_OF_DELIVERIES_REQUEST =
  "FETCH_TYPE_OF_DELIVERIES_REQUEST";
export const FETCH_TYPE_OF_DELIVERIES_ERROR = "FETCH_TYPE_OF_DELIVERIES_ERROR";
export const FETCH_TYPE_OF_DELIVERIES_SUCCESS =
  "FETCH_TYPE_OF_DELIVERIES_SUCCESS";

export const CREATE_TYPE_OF_DELIVERY_REQUEST =
  "CREATE_TYPE_OF_DELIVERY_REQUEST";
export const CREATE_TYPE_OF_DELIVERY_ERROR = "CREATE_TYPE_OF_DELIVERY_ERROR";
export const CREATE_TYPE_OF_DELIVERY_SUCCESS =
  "CREATE_TYPE_OF_DELIVERY_SUCCESS";

export const DELETE_TYPE_OF_DELIVERY_REQUEST =
  "DELETE_TYPE_OF_DELIVERY_REQUEST";
export const DELETE_TYPE_OF_DELIVERY_ERROR = "DELETE_TYPE_OF_DELIVERY_ERROR";
export const DELETE_TYPE_OF_DELIVERY_SUCCESS =
  "DELETE_TYPE_OF_DELIVERY_SUCCESS";

export const UPDATE_TYPE_OF_DELIVERY_REQUEST =
  "UPDATE_TYPE_OF_DELIVERY_REQUEST";
export const UPDATE_TYPE_OF_DELIVERY_ERROR = "UPDATE_TYPE_OF_DELIVERY_ERROR";
export const UPDATE_TYPE_OF_DELIVERY_SUCCESS =
  "UPDATE_TYPE_OF_DELIVERY_SUCCESS";

export const FETCH_TYPE_OF_DELIVERY_REQUEST = "FETCH_TYPE_OF_DELIVERY_REQUEST";
export const FETCH_TYPE_OF_DELIVERY_ERROR = "FETCH_TYPE_OF_DELIVERY_ERROR";
export const FETCH_TYPE_OF_DELIVERY_SUCCESS = "FETCH_TYPE_OF_DELIVERY_SUCCESS";

export const EDIT_TYPE_OF_DELIVERY = "EDIT_TYPE_OF_DELIVERY";
export const RESET_TYPE_OF_DELIVERY_FORM = "RESET_TYPE_OF_DELIVERY_FORM";
export const SEARCH_TYPE_OF_DELIVERIES = "SEARCH_TYPE_OF_DELIVERIES";
