export const FETCH_TYPE_OF_ORGANIZATIONS_REQUEST =
  "FETCH_TYPE_OF_ORGANIZATIONS_REQUEST";
export const FETCH_TYPE_OF_ORGANIZATIONS_ERROR =
  "FETCH_TYPE_OF_ORGANIZATIONS_ERROR";
export const FETCH_TYPE_OF_ORGANIZATIONS_SUCCESS =
  "FETCH_TYPE_OF_ORGANIZATIONS_SUCCESS";

export const CREATE_TYPE_OF_ORGANIZATION_REQUEST =
  "CREATE_TYPE_OF_ORGANIZATION_REQUEST";
export const CREATE_TYPE_OF_ORGANIZATION_ERROR =
  "CREATE_TYPE_OF_ORGANIZATION_ERROR";
export const CREATE_TYPE_OF_ORGANIZATION_SUCCESS =
  "CREATE_TYPE_OF_ORGANIZATION_SUCCESS";

export const DELETE_TYPE_OF_ORGANIZATION_REQUEST =
  "DELETE_TYPE_OF_ORGANIZATION_REQUEST";
export const DELETE_TYPE_OF_ORGANIZATION_ERROR =
  "DELETE_TYPE_OF_ORGANIZATION_ERROR";
export const DELETE_TYPE_OF_ORGANIZATION_SUCCESS =
  "DELETE_TYPE_OF_ORGANIZATION_SUCCESS";

export const UPDATE_TYPE_OF_ORGANIZATION_REQUEST =
  "UPDATE_TYPE_OF_ORGANIZATION_REQUEST";
export const UPDATE_TYPE_OF_ORGANIZATION_ERROR =
  "UPDATE_TYPE_OF_ORGANIZATION_ERROR";
export const UPDATE_TYPE_OF_ORGANIZATION_SUCCESS =
  "UPDATE_TYPE_OF_ORGANIZATION_SUCCESS";

export const FETCH_TYPE_OF_ORGANIZATION_REQUEST =
  "FETCH_TYPE_OF_ORGANIZATION_REQUEST";
export const FETCH_TYPE_OF_ORGANIZATION_ERROR =
  "FETCH_TYPE_OF_ORGANIZATION_ERROR";
export const FETCH_TYPE_OF_ORGANIZATION_SUCCESS =
  "FETCH_TYPE_OF_ORGANIZATION_SUCCESS";

export const EDIT_TYPE_OF_ORGANIZATION = "EDIT_TYPE_OF_ORGANIZATION";
export const RESET_TYPE_OF_ORGANIZATION_FORM =
  "RESET_TYPE_OF_ORGANIZATION_FORM";
export const SEARCH_TYPE_OF_ORGANIZATIONS = "SEARCH_TYPE_OF_ORGANIZATIONS";
